### ISSUE TITLE
Fix security vulnerabilities

### ISSUE THREAD

**Issue by akafazov** [Daiteap/daiteap-ui#11]
Secret scan revealed vulnerabilities:
- [x] https://github.com/Daiteap/daiteap-platform/security/secret-scanning 
- [x] [Daiteap Platform](https://github.com/Daiteap/daiteap-platform/security/code-scanning)
- [x] [Daiteap UI Codacy](https://app.codacy.com/gh/Daiteap/daiteap-ui/commit?bid=35768779&cid=740550235)
- [x] [Daiteap UI Dependabot](https://github.com/Daiteap/daiteap-ui/security/dependabot)
- [x] Add lint file to repository

**Comment by bpavlov-daiteap** [comment]
PR:
https://github.com/Daiteap/daiteap-ui/pull/6
https://github.com/Daiteap/daiteap-ui/pull/10
