### ISSUE TITLE
Create Devcontainer Env

### ISSUE THREAD

**Issue by vikig07** [Daiteap/daiteap-ui#15]
- [x] daiteap-ui
- [x] daiteap-cli

**Comment by ignatov17** [comment]
devcontainer envs work fine, according the documentation.

1 typo in DAITEAP-UI documentation:
On line 38 in README.md:    '.devcontainer/buils-ui.sh' to be '.devcontainer/build-ui.sh'

**Comment by vikig07** [comment]
Fixed the typo - #19
